### ISSUE TITLE
ConcurrencyUtils: java.lang.ArrayIndexOutOfBoundsException on waitForCompletion()

### ISSUE THREAD

**Issue by stevenjwest** [rwl/ParallelColt#14]
Hi I am having an issue where I get an java.lang.ArrayIndexOutOfBoundsException in edu.emory.mathcs.utils.pc.ConcurrencyUtils from ParallelColt v0.11.4:

```
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 8988800
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at edu.emory.mathcs.utils.pc.ConcurrencyUtils.waitForCompletion(ConcurrencyUtils.java:176)
	at edu.emory.mathcs.restoretools.iterative.wpl.WPLFloatIterativeDeconvolver3D.convolveFD(WPLFloatIterativeDeconvolver3D.java:443)
	at edu.emory.mathcs.restoretools.iterative.wpl.WPLFloatIterativeDeconvolver3D.deconvolve(WPLFloatIterativeDeconvolver3D.java:313)
```

Does anyone have any idea why this problem may be occurring?  It is occurring on the `waitForCompletion()` method:

```
    /**
     * Waits for all threads to complete computation.
     * 
     * @param futures
     *            handles to running threads
     */
    public static void waitForCompletion(Future<?>[] futures) {
        int size = futures.length;
        try {
            for (int j = 0; j < size; j++) {
                futures[j].get();
            }
        } catch (ExecutionException ex) {
            ex.printStackTrace();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
```

The exception is thrown on the `futures[j].get();` line, however I wonder if the problem is to do with JTransforms?  As in ImageJ the current build uses version 2.4, but I believe this copy of ConcurrencyUtils is designed to work with Transforms v3.1?

Although I get the error, the deconvolution I am running still seems to continue.

As you can see, I am using the ParallelIterativeDeconvolution code designed by Piotr Wendykier - I have changed its dependency from its internal `edu.emory.mathcs.utils.ConcurrencyUtils` to the `edu.emory.mathcs.utils.pc.ConcurrencyUtils` found in ParallelColt v0.11.4.  You can see this in a fork repo I made here - https://github.com/stevenjwest/iterativedeconv

* I changed this dependency because the code is run in imagej, and imagej contains other JARs that also contain the `edu.emory.mathcs.utils.ConcurrencyUtils` package/class!  Specifically:

    + `net.sourceforge.jplasma:jplasma:jar:1.2.0`
    
    + `net.sourceforge.jtransforms:jtransforms:jar:2.4.0`

**Comment by stevenjwest** [comment]
Apologies, I realised the error is actually in ParallelIterativeDeconvolution:

```
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 8988800
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at edu.emory.mathcs.utils.pc.ConcurrencyUtils.waitForCompletion(ConcurrencyUtils.java:176)
	at edu.emory.mathcs.restoretools.iterative.wpl.WPLFloatIterativeDeconvolver3D.convolveFD(WPLFloatIterativeDeconvolver3D.java:443)
	at edu.emory.mathcs.restoretools.iterative.wpl.WPLFloatIterativeDeconvolver3D.deconvolve(WPLFloatIterativeDeconvolver3D.java:313)
...
Caused by: java.lang.ArrayIndexOutOfBoundsException: 8988800
	at edu.emory.mathcs.restoretools.iterative.wpl.WPLFloatIterativeDeconvolver3D$1.run(WPLFloatIterativeDeconvolver3D.java:434)
```

Thanks!
